on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: 'Optional: Commit, branch etc.'  
        required: false
      skip-tests:
        type: boolean
        required: false
        default: false
      environment:
        type: environment

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: echo "${{ inputs.environment }}"
        shell: bash

  foo:
    runs-on: ubuntu-latest
    environment: foo
    needs:
      - test
    steps:
      - name: Foo
        run: echo "${{ inputs.environment }}"
        shell: bash
  bar:
    runs-on: ubuntu-latest
    environment: bar
    needs:
      - test
    steps:
      - name: Foo
        run: echo "${{ inputs.environment }}"
        shell: bash
